// AUTO-GENERATED by scripts/gen-projects.mjs — do not edit by hand.
// Regenerate after changing project images: node scripts/gen-projects.mjs
import type { StaticImageData } from "next/image";

import img_terraza_pangea_0 from "@/public/proyectos/terraza-pangea/EA_AES_SRPA_24_001AV2_5260_P-e1771974642904.webp";
import img_terraza_pangea_1 from "@/public/proyectos/terraza-pangea/EA_AES_SRPA_24_002AV2_5278_P.webp";
import img_terraza_pangea_2 from "@/public/proyectos/terraza-pangea/EA_AES_SRPA_24_003AV2_5295_P.webp";
import img_terraza_pangea_3 from "@/public/proyectos/terraza-pangea/EA_AES_SRPA_24_004AV2_5324_P-scaled-1.webp";
import img_terraza_pangea_4 from "@/public/proyectos/terraza-pangea/EA_AES_SRPA_24_005AV2_5310_P-scaled-1.webp";
import img_kampai_0 from "@/public/proyectos/kampai/anta-arquitectura-comercial-kampai-1-scaled.webp";
import img_kampai_1 from "@/public/proyectos/kampai/anta-arquitectura-comercial-kampai-2-scaled.webp";
import img_kampai_2 from "@/public/proyectos/kampai/anta-arquitectura-comercial-kampai-3.webp";
import img_kampai_3 from "@/public/proyectos/kampai/anta-arquitectura-comercial-kampai-4-scaled.webp";
import img_kampai_4 from "@/public/proyectos/kampai/anta-arquitectura-comercial-kampai-5-scaled.webp";
import img_kampai_5 from "@/public/proyectos/kampai/anta-arquitectura-comercial-kampai-6.webp";
import img_cafe_laurel_0 from "@/public/proyectos/cafe-laurel/anta-arquitectura-comercial-cafe-laurel-1.webp";
import img_cafe_laurel_1 from "@/public/proyectos/cafe-laurel/anta-arquitectura-comercial-cafe-laurel-2.webp";
import img_cafe_laurel_2 from "@/public/proyectos/cafe-laurel/anta-arquitectura-comercial-cafe-laurel-3.webp";
import img_cafe_laurel_3 from "@/public/proyectos/cafe-laurel/anta-arquitectura-comercial-cafe-laurel-4.webp";
import img_cafe_laurel_4 from "@/public/proyectos/cafe-laurel/anta-arquitectura-comercial-cafe-laurel-5.webp";
import img_nailz_0 from "@/public/proyectos/nailz/anta-arquitectura-comercial-nailz-1.webp";
import img_nailz_1 from "@/public/proyectos/nailz/anta-arquitectura-comercial-nailz-2.webp";
import img_nailz_2 from "@/public/proyectos/nailz/anta-arquitectura-comercial-nailz-3.webp";
import img_nailz_3 from "@/public/proyectos/nailz/anta-arquitectura-comercial-nailz-4.webp";
import img_nailz_4 from "@/public/proyectos/nailz/anta-arquitectura-comercial-nailz-5.webp";
import img_ludoteca_valle_alto_0 from "@/public/proyectos/ludoteca-valle-alto/arquitectura-corporativo-ludoteca-1-e1773265872463.webp";
import img_ludoteca_valle_alto_1 from "@/public/proyectos/ludoteca-valle-alto/arquitectura-corporativo-ludoteca-2.webp";
import img_ludoteca_valle_alto_2 from "@/public/proyectos/ludoteca-valle-alto/arquitectura-corporativo-ludoteca-3.webp";
import img_ludoteca_valle_alto_3 from "@/public/proyectos/ludoteca-valle-alto/arquitectura-corporativo-ludoteca-5.webp";
import img_ludoteca_valle_alto_4 from "@/public/proyectos/ludoteca-valle-alto/arquitectura-corporativo-ludoteca-6.webp";
import img_ludoteca_valle_alto_5 from "@/public/proyectos/ludoteca-valle-alto/arquitectura-corporativo-ludoteca-7.webp";
import img_valle_alto_club_de_golf_0 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-1.webp";
import img_valle_alto_club_de_golf_1 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-2.webp";
import img_valle_alto_club_de_golf_2 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-3.webp";
import img_valle_alto_club_de_golf_3 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-4.webp";
import img_valle_alto_club_de_golf_4 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-5.webp";
import img_valle_alto_club_de_golf_5 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-6.webp";
import img_valle_alto_club_de_golf_6 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-7.webp";
import img_valle_alto_club_de_golf_7 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-8.webp";
import img_valle_alto_club_de_golf_8 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-9.webp";
import img_valle_alto_club_de_golf_9 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-10.webp";
import img_valle_alto_club_de_golf_10 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-12.webp";
import img_valle_alto_club_de_golf_11 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes-13.webp";
import img_valle_alto_club_de_golf_12 from "@/public/proyectos/valle-alto-club-de-golf/anta-arquitectura-corporativo-valle-alto-areas-comunes.webp";
import img_crispy_pollo_0 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-1.webp";
import img_crispy_pollo_1 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-2.webp";
import img_crispy_pollo_2 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-3.webp";
import img_crispy_pollo_3 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-4.webp";
import img_crispy_pollo_4 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-5.webp";
import img_crispy_pollo_5 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-6.webp";
import img_crispy_pollo_6 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-7.webp";
import img_crispy_pollo_7 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-8.webp";
import img_crispy_pollo_8 from "@/public/proyectos/crispy-pollo/anta-arquitectura-comercial-crispy-pollo-9.webp";
import img_e_80_0 from "@/public/proyectos/e-80/arquitectura-corporativo-e80-2.webp";
import img_e_80_1 from "@/public/proyectos/e-80/arquitectura-corporativo-e80-3.webp";
import img_e_80_2 from "@/public/proyectos/e-80/arquitectura-corporativo-e80-4.webp";
import img_e_80_3 from "@/public/proyectos/e-80/arquitectura-corporativo-e80-5.webp";
import img_e_80_4 from "@/public/proyectos/e-80/arquitectura-corporativo-e80-6.webp";
import img_e_80_5 from "@/public/proyectos/e-80/arquitectura-corporativo-e80-7.webp";
import img_e_80_6 from "@/public/proyectos/e-80/arquitectura-corporativo-e80-8.webp";
import img_e_80_7 from "@/public/proyectos/e-80/EA_AES_SOE80_26_008AV2D_0150-e1774392988765.webp";
import img_edificio_vh_0 from "@/public/proyectos/edificio-vh/anta-arquitectura-corporativo-edificio-vh-1.webp";
import img_edificio_vh_1 from "@/public/proyectos/edificio-vh/anta-arquitectura-corporativo-edificio-vh-2.webp";
import img_oficinas_majadma_0 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_001AV2_3492_P-e1772727087278.webp";
import img_oficinas_majadma_1 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_003AV2_3480_P.webp";
import img_oficinas_majadma_2 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_004AV2_3498_P.webp";
import img_oficinas_majadma_3 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_005AV2_3511_P.webp";
import img_oficinas_majadma_4 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_006AV2_3507_P.webp";
import img_oficinas_majadma_5 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_007AV2_3520_P.webp";
import img_oficinas_majadma_6 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_008AV2_3523_P.webp";
import img_oficinas_majadma_7 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_009AV2_3529_P.webp";
import img_oficinas_majadma_8 from "@/public/proyectos/oficinas-majadma/EA_AES_SOMA_23_010AV2_3539_P.webp";
import img_tp_zentralia_0 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-2.webp";
import img_tp_zentralia_1 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-3.webp";
import img_tp_zentralia_2 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-4.webp";
import img_tp_zentralia_3 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-5.webp";
import img_tp_zentralia_4 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-6.webp";
import img_tp_zentralia_5 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-7.webp";
import img_tp_zentralia_6 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-8.webp";
import img_tp_zentralia_7 from "@/public/proyectos/tp-zentralia/arquitectura-corporativo-tp-zentralia-9.webp";
import img_valle_alto_club_de_golf_gimnasio_0 from "@/public/proyectos/valle-alto-club-de-golf-gimnasio/valle-alto-gimnasio-2.webp";
import img_valle_alto_club_de_golf_gimnasio_1 from "@/public/proyectos/valle-alto-club-de-golf-gimnasio/valle-alto-gimnasio-3.webp";
import img_valle_alto_club_de_golf_gimnasio_2 from "@/public/proyectos/valle-alto-club-de-golf-gimnasio/valle-alto-gimnasio-4.webp";
import img_valle_alto_club_de_golf_gimnasio_3 from "@/public/proyectos/valle-alto-club-de-golf-gimnasio/valle-alto-gimnasio-5.webp";
import img_valle_alto_club_de_golf_gimnasio_4 from "@/public/proyectos/valle-alto-club-de-golf-gimnasio/valle-alto-gimnasio-6.webp";
import img_valle_alto_club_de_golf_gimnasio_5 from "@/public/proyectos/valle-alto-club-de-golf-gimnasio/valle-alto-gimnasio.webp";

export type Categoria = "comercial" | "corporativo" | "residencial";

export interface Project {
  slug: string;
  nombre: string;
  /** Pendiente de categorizar (se asignará después). */
  categoria: Categoria | null;
  featured: boolean;
  cover: StaticImageData;
  galeria: StaticImageData[];
}

export const projects: Project[] = [
  {
    slug: "terraza-pangea",
    nombre: "Terraza Pangea",
    categoria: null,
    featured: true,
    cover: img_terraza_pangea_4,
    galeria: [img_terraza_pangea_0, img_terraza_pangea_1, img_terraza_pangea_2, img_terraza_pangea_3],
  },
  {
    slug: "kampai",
    nombre: "Kampai",
    categoria: null,
    featured: true,
    cover: img_kampai_0,
    galeria: [img_kampai_1, img_kampai_2, img_kampai_3, img_kampai_4, img_kampai_5],
  },
  {
    slug: "cafe-laurel",
    nombre: "Café Laurel",
    categoria: null,
    featured: true,
    cover: img_cafe_laurel_0,
    galeria: [img_cafe_laurel_1, img_cafe_laurel_2, img_cafe_laurel_3, img_cafe_laurel_4],
  },
  {
    slug: "nailz",
    nombre: "Nailz",
    categoria: null,
    featured: true,
    cover: img_nailz_1,
    galeria: [img_nailz_0, img_nailz_2, img_nailz_3, img_nailz_4],
  },
  {
    slug: "ludoteca-valle-alto",
    nombre: "Ludoteca Valle Alto",
    categoria: null,
    featured: true,
    cover: img_ludoteca_valle_alto_5,
    galeria: [img_ludoteca_valle_alto_0, img_ludoteca_valle_alto_1, img_ludoteca_valle_alto_2, img_ludoteca_valle_alto_3, img_ludoteca_valle_alto_4],
  },
  {
    slug: "valle-alto-club-de-golf",
    nombre: "Valle Alto Club de Golf",
    categoria: null,
    featured: true,
    cover: img_valle_alto_club_de_golf_1,
    galeria: [img_valle_alto_club_de_golf_0, img_valle_alto_club_de_golf_2, img_valle_alto_club_de_golf_3, img_valle_alto_club_de_golf_4, img_valle_alto_club_de_golf_5, img_valle_alto_club_de_golf_6, img_valle_alto_club_de_golf_7, img_valle_alto_club_de_golf_8, img_valle_alto_club_de_golf_9, img_valle_alto_club_de_golf_10, img_valle_alto_club_de_golf_11, img_valle_alto_club_de_golf_12],
  },
  {
    slug: "crispy-pollo",
    nombre: "Crispy Pollo",
    categoria: null,
    featured: false,
    cover: img_crispy_pollo_0,
    galeria: [img_crispy_pollo_1, img_crispy_pollo_2, img_crispy_pollo_3, img_crispy_pollo_4, img_crispy_pollo_5, img_crispy_pollo_6, img_crispy_pollo_7, img_crispy_pollo_8],
  },
  {
    slug: "e-80",
    nombre: "E-80",
    categoria: null,
    featured: false,
    cover: img_e_80_0,
    galeria: [img_e_80_1, img_e_80_2, img_e_80_3, img_e_80_4, img_e_80_5, img_e_80_6, img_e_80_7],
  },
  {
    slug: "edificio-vh",
    nombre: "Edificio VH",
    categoria: null,
    featured: false,
    cover: img_edificio_vh_0,
    galeria: [img_edificio_vh_1],
  },
  {
    slug: "oficinas-majadma",
    nombre: "Oficinas MAJADMA",
    categoria: null,
    featured: false,
    cover: img_oficinas_majadma_1,
    galeria: [img_oficinas_majadma_0, img_oficinas_majadma_2, img_oficinas_majadma_3, img_oficinas_majadma_4, img_oficinas_majadma_5, img_oficinas_majadma_6, img_oficinas_majadma_7, img_oficinas_majadma_8],
  },
  {
    slug: "tp-zentralia",
    nombre: "TP Zentralia",
    categoria: null,
    featured: false,
    cover: img_tp_zentralia_0,
    galeria: [img_tp_zentralia_1, img_tp_zentralia_2, img_tp_zentralia_3, img_tp_zentralia_4, img_tp_zentralia_5, img_tp_zentralia_6, img_tp_zentralia_7],
  },
  {
    slug: "valle-alto-club-de-golf-gimnasio",
    nombre: "Valle Alto Gimnasio",
    categoria: null,
    featured: false,
    cover: img_valle_alto_club_de_golf_gimnasio_5,
    galeria: [img_valle_alto_club_de_golf_gimnasio_0, img_valle_alto_club_de_golf_gimnasio_1, img_valle_alto_club_de_golf_gimnasio_2, img_valle_alto_club_de_golf_gimnasio_3, img_valle_alto_club_de_golf_gimnasio_4],
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

/** The next project in order (wraps around) — for the "siguiente proyecto" link. */
export function getNextProject(slug: string): Project {
  const i = projects.findIndex((p) => p.slug === slug);
  return projects[(i + 1) % projects.length];
}
